added gitlab tests for dagger duplication

diff --git a/apps/dagger/Makefile.venv b/apps/dagger/Makefile.venv
--- a/apps/dagger/Makefile.venv
+++ b/apps/dagger/Makefile.venv
@@ -25,6 +25,9 @@ test-local-workgroup-sizes:
 test-correctness:
 	source daggerpy/bin/activate ; IRIS_HISTORY=1 IRIS_INSTALL_ROOT=$(IRIS) SKIP_SETUP=1 bash ./test_correctness.sh 1> test-out.txt 2>&1 
 
+test-duplication:
+	source daggerpy/bin/activate ; IRIS_HISTORY=1 IRIS_INSTALL_ROOT=$(IRIS) SKIP_SETUP=1 bash ./test_duplication_feature.sh 1> test-out.txt 2>&1 
+
 validate-run-policy:
 	rm -rf errors.txt ; touch errors.txt ;
 	if [ -e test-out.txt ]; then \
@@ -53,6 +56,23 @@ validate-test-correctness:
     echo 'No output' >> errors.txt ; \
     fi ; \
 	for f in $(shell ls ${TEST_CORRECTNESS_OUT_DIR}); do \
+        echo "Validating Json Schema for file $${f}." \
+        $(GIT_ROOT)/utils/validate_schema.py -i $${f} -s $(GIT_ROOT)/schema/dagger.schema.json || echo Json Validation failed for $${f} >> errors.txt ; \
+    done ; \
+    echo "Finished: $$(date)" ; \
+	echo "Errors:" $$(wc -l < errors.txt)  ;
+
+validate-test-duplication:
+	rm -rf errors.txt ; touch errors.txt ;
+	if [ -e test-out.txt ]; then \
+	grep -e '\[E\]' test-out.txt > errors.txt ; \
+    grep -e 'No such file or directory' test-out.txt >> errors.txt ; \
+	grep -e 'Segmentation fault' test-out.txt >> errors.txt ; \
+	grep -e 'EnvironmentLocationNotFound' test-out.txt >> errors.txt ; \
+    else \
+    echo 'No output' >> errors.txt ; \
+    fi ; \
+	for f in $(shell ls ${TEST_DUPLICATION_OUT_DIR}); do \
         echo "Validating Json Schema for file $${f}." \
         $(GIT_ROOT)/utils/validate_schema.py -i $${f} -s $(GIT_ROOT)/schema/dagger.schema.json || echo Json Validation failed for $${f} >> errors.txt ; \
     done ; \
